//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.CannedResponses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.CannedResponses.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNewButtonText {
            get {
                return ResourceManager.GetString("AddNewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Make your suggestion again..
        /// </summary>
        public static string AddNewSuggestionFailedMessage {
            get {
                return ResourceManager.GetString("AddNewSuggestionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion added!.
        /// </summary>
        public static string AddNewSuggestionSuccessMessage {
            get {
                return ResourceManager.GetString("AddNewSuggestionSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try adding a response again..
        /// </summary>
        public static string AddUserResponseFailedMessage {
            get {
                return ResourceManager.GetString("AddUserResponseFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully!.
        /// </summary>
        public static string AddUserResponseSuccessMessage {
            get {
                return ResourceManager.GetString("AddUserResponseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string ApproveButtonTitle {
            get {
                return ResourceManager.GetString("ApproveButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved: {0} by {1}.
        /// </summary>
        public static string ApprovedAdminCardLabelText {
            get {
                return ResourceManager.GetString("ApprovedAdminCardLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved: {0}.
        /// </summary>
        public static string ApprovedCardLabelText {
            get {
                return ResourceManager.GetString("ApprovedCardLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Request approved**.
        /// </summary>
        public static string ApprovedRequestRefreshCardTitle {
            get {
                return ResourceManager.GetString("ApprovedRequestRefreshCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string ApprovedRequestStatusText {
            get {
                return ResourceManager.GetString("ApprovedRequestStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ApproveToggleCardCategoryTitle {
            get {
                return ResourceManager.GetString("ApproveToggleCardCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type category.
        /// </summary>
        public static string ApproveToggleCardLabelPlaceholder {
            get {
                return ResourceManager.GetString("ApproveToggleCardLabelPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type questions separated by semicolons (;).
        /// </summary>
        public static string ApproveToggleCardQuestionsPlaceholder {
            get {
                return ResourceManager.GetString("ApproveToggleCardQuestionsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question(s).
        /// </summary>
        public static string ApproveToggleCardQuestionsTitle {
            get {
                return ResourceManager.GetString("ApproveToggleCardQuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type response.
        /// </summary>
        public static string ApproveToggleCardResponsePlaceholder {
            get {
                return ResourceManager.GetString("ApproveToggleCardResponsePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string ApproveToggleCardResponseTitle {
            get {
                return ResourceManager.GetString("ApproveToggleCardResponseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ApproveToggleCardSubmitButtonTitle {
            get {
                return ResourceManager.GetString("ApproveToggleCardSubmitButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with {0}.
        /// </summary>
        public static string ChatTextButton {
            get {
                return ResourceManager.GetString("ChatTextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company responses.
        /// </summary>
        public static string CompanyResponsesMenuText {
            get {
                return ResourceManager.GetString("CompanyResponsesMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmButtonText {
            get {
                return ResourceManager.GetString("ConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action confirmation.
        /// </summary>
        public static string DialogConfirmHeader {
            get {
                return ResourceManager.GetString("DialogConfirmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to confirm this action?.
        /// </summary>
        public static string DialogConfirmText {
            get {
                return ResourceManager.GetString("DialogConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try updating again..
        /// </summary>
        public static string EditUserResponseFailedMessage {
            get {
                return ResourceManager.GetString("EditUserResponseFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update saved!.
        /// </summary>
        public static string EditUserResponseSuccessMessage {
            get {
                return ResourceManager.GetString("EditUserResponseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again in a few minutes..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category, question and response fields are mandatory to approve the response..
        /// </summary>
        public static string ErrorMessageOnApprove {
            get {
                return ResourceManager.GetString("ErrorMessageOnApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App does not support any bot commands, please use messaging extension for better results..
        /// </summary>
        public static string ErrorWhenMessageInChannel {
            get {
                return ResourceManager.GetString("ErrorWhenMessageInChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string FieldRequiredMessage {
            get {
                return ResourceManager.GetString("FieldRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot access this page. Contact your IT admin for permission..
        /// </summary>
        public static string ForbiddenErrorMessage {
            get {
                return ResourceManager.GetString("ForbiddenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again in a few minutes..
        /// </summary>
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your responses.
        /// </summary>
        public static string ManageYourResponsesTitleText {
            get {
                return ResourceManager.GetString("ManageYourResponsesTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max limit reached for approved company responses. Please contact your admin to get more details..
        /// </summary>
        public static string MaxCompanyResponseMessage {
            get {
                return ResourceManager.GetString("MaxCompanyResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create maximum 200 user responses.
        /// </summary>
        public static string MaxResponsesMessage {
            get {
                return ResourceManager.GetString("MaxResponsesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your responses.
        /// </summary>
        public static string MyResponsesText {
            get {
                return ResourceManager.GetString("MyResponsesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Thanks for suggesting a company response.**.
        /// </summary>
        public static string NotificationCardApprovedOrRejectedTitle {
            get {
                return ResourceManager.GetString("NotificationCardApprovedOrRejectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Category:**.
        /// </summary>
        public static string NotificationCardLabelText {
            get {
                return ResourceManager.GetString("NotificationCardLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Question:**.
        /// </summary>
        public static string NotificationCardQuestion {
            get {
                return ResourceManager.GetString("NotificationCardQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Comment**.
        /// </summary>
        public static string NotificationCardRemark {
            get {
                return ResourceManager.GetString("NotificationCardRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Request  rejected**.
        /// </summary>
        public static string NotificationCardRequestReject {
            get {
                return ResourceManager.GetString("NotificationCardRequestReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested by {0}.
        /// </summary>
        public static string NotificationCardRequestText {
            get {
                return ResourceManager.GetString("NotificationCardRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Response:**.
        /// </summary>
        public static string NotificationCardResponse {
            get {
                return ResourceManager.GetString("NotificationCardResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}.
        /// </summary>
        public static string NotificationCardStatusText {
            get {
                return ResourceManager.GetString("NotificationCardStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **New! Company response for approval**.
        /// </summary>
        public static string NotificationRequestCardContentText {
            get {
                return ResourceManager.GetString("NotificationRequestCardContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question(s).
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested by {0}.
        /// </summary>
        public static string RefreshedNotificationCardRequestText {
            get {
                return ResourceManager.GetString("RefreshedNotificationCardRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshLinkText {
            get {
                return ResourceManager.GetString("RefreshLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string RejectButtonTitle {
            get {
                return ResourceManager.GetString("RejectButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected: {0} by {1}.
        /// </summary>
        public static string RejectedAdminCardLabelText {
            get {
                return ResourceManager.GetString("RejectedAdminCardLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected: {0}.
        /// </summary>
        public static string RejectedCardLabelText {
            get {
                return ResourceManager.GetString("RejectedCardLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string RejectedRequestStatusText {
            get {
                return ResourceManager.GetString("RejectedRequestStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain why this was rejected (optional).
        /// </summary>
        public static string RejectToggleCardRemarkPlaceholder {
            get {
                return ResourceManager.GetString("RejectToggleCardRemarkPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string RejectToggleCardRemarkTitle {
            get {
                return ResourceManager.GetString("RejectToggleCardRemarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string RejectToggleCardSubmitButtonTitle {
            get {
                return ResourceManager.GetString("RejectToggleCardSubmitButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested on.
        /// </summary>
        public static string RequestedOnText {
            get {
                return ResourceManager.GetString("RequestedOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string RequestsMenuText {
            get {
                return ResourceManager.GetString("RequestsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest.
        /// </summary>
        public static string SuggestButtonText {
            get {
                return ResourceManager.GetString("SuggestButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest new.
        /// </summary>
        public static string SuggestNewButtonText {
            get {
                return ResourceManager.GetString("SuggestNewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type category.
        /// </summary>
        public static string TypeCategoryPlaceholder {
            get {
                return ResourceManager.GetString("TypeCategoryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type questions separated by semicolons (;).
        /// </summary>
        public static string TypeQuestionPlaceholder {
            get {
                return ResourceManager.GetString("TypeQuestionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type response.
        /// </summary>
        public static string TypeResponsePlaceholder {
            get {
                return ResourceManager.GetString("TypeResponsePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again in a few minutes..
        /// </summary>
        public static string UnauthorizedErrorMessage {
            get {
                return ResourceManager.GetString("UnauthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send update.
        /// </summary>
        public static string UpdateAndShareButtonText {
            get {
                return ResourceManager.GetString("UpdateAndShareButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string UpdateButtonText {
            get {
                return ResourceManager.GetString("UpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I don&apos;t support bot commands..
        /// </summary>
        public static string UserCustomMessage {
            get {
                return ResourceManager.GetString("UserCustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Chat with requester..
        /// </summary>
        public static string WelcomeCardChatRequestorContentText {
            get {
                return ResourceManager.GetString("WelcomeCardChatRequestorContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the small version of my icon near your message formatting options to get started..
        /// </summary>
        public static string WelcomeCardContent {
            get {
                return ResourceManager.GetString("WelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I can assist you in managing user submitted responses..
        /// </summary>
        public static string WelcomeCardContentForAdmin {
            get {
                return ResourceManager.GetString("WelcomeCardContentForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Edit response response before final submission..
        /// </summary>
        public static string WelcomeCardLabelContentText {
            get {
                return ResourceManager.GetString("WelcomeCardLabelContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Manager your personal responses..
        /// </summary>
        public static string WelcomeCardResponseListContentText {
            get {
                return ResourceManager.GetString("WelcomeCardResponseListContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Suggest new responses to use across company and check your request status..
        /// </summary>
        public static string WelcomeCardSuggestedContentText {
            get {
                return ResourceManager.GetString("WelcomeCardSuggestedContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Suggest new response to add in company responses..
        /// </summary>
        public static string WelcomeCardSuggestResponseContentText {
            get {
                return ResourceManager.GetString("WelcomeCardSuggestResponseContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some of the things that I can do:.
        /// </summary>
        public static string WelcomeCardThingsContentText {
            get {
                return ResourceManager.GetString("WelcomeCardThingsContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! Hello, I can help you to manage your quick responses to search and share in chat messages..
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
    }
}
